version: '3.8'
services:
  mhl-amataya-mongo-db:
    image: mongo:4.4
    container_name: amataya-mongo-db
    restart: always
    ports:
      - '18018:27017'
    volumes:
      - './dbdata/amataya:/data/db'
  mhl-dev-mongo-db:
    image: mongo:4.4
    container_name: dev-mongo-db
    restart: always
    ports:
      - '18019:27017'
    volumes:
      - './dbdata/dev:/data/db'




