version: '3.8'
services:
  mongo-db:
    image: mongo:4.4
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: always
    ports:
      - '${DOCKER_PORT}:27017'
    volumes:
      - '${DOCKER_VOLUMES_DIR}:/data/db'




